apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-csi  # Specify the storage class here
  resources:
    requests:
      storage: 800Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: models-pod
spec:
  containers:
  - name: models-container
    image: ubuntu:22.04
    command: ["/bin/bash", "-c"]
    args: ["sleep infinity"]
    volumeMounts:
    - name: models-volume
      mountPath: /models
  volumes:
  - name: models-volume
    persistentVolumeClaim:
      claimName: models-pvc
